# Reading/writing data from diff sources - excel, jason

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r'C:\Users\SACHIN KUMAR\Documents\survery\survey_results_schema.csv')
df = pd.read_csv(r'C:\Users\SACHIN KUMAR\Documents\survery\survey_results_public.csv')

In [4]:
filt = (df['Country']=='India')
india_df = df.loc[filt]
india_df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,...,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3

In [7]:
df2 = india_df.to_csv(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.csv')# will create a new csv  file with the above data

In [8]:
pd.read_csv(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.csv') # all countr== india was saved with another csv and
#pulled here

,Unnamed: 0,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,6,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
1,21,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
2,57,58,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,...,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
3,62,63,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
4,147,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8398,64391,54757,NaN,Yes,NaN,18,NaN,NaN,NaN,India,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
8399,64398,55407,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8400,64439,62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
8401,64442,62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
8402,64452,64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
india_df.to_csv(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.tsv', sep ='\t')
# files saved with space

In [10]:
!pip install xlwt # xlwt will write to an older XLS excel format bt if u want to write to a newer xlsx excel formate
# then wil also need toinstall open pi excel.if we want to read xl files then install xlrd

ERROR: Invalid requirement: '#'

In [11]:
!pip install xlwt openpyxl xlrd

Requirement already satisfied: xlwt in c:\users\sachin kumar\anaconda3\lib\site-packages (1.3.0)
Requirement already satisfied: openpyxl in c:\users\sachin kumar\anaconda3\lib\site-packages (3.0.5)
Requirement already satisfied: xlrd in c:\users\sachin kumar\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: jdcal in c:\users\sachin kumar\anaconda3\lib\site-packages (from openpyxl) (1.4.1)
Requirement already satisfied: et-xmlfile in c:\users\sachin kumar\anaconda3\lib\site-packages (from openpyxl) (1.0.1)

In [13]:
india_df.to_excel(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.xlsx')

In [14]:
test = pd.read_excel(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.xlsx')

In [15]:
test = pd.read_excel(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.xlsx', index_col = 'Respondent')

In [16]:
test

,Unnamed: 0,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
7,6,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
22,21,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
58,57,I am a developer by profession,Yes,NaN,22,NaN,NaN,NaN,India,Indian rupee,...,Neither easy nor difficult,Too long,NaN,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN
63,62,I am a student who is learning to code,Yes,21.0,17,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,NaN,Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Not applicable - I did not use Stack Overflow ...,NaN,4,NaN
149,147,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,70.0,5,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54757,64391,NaN,Yes,NaN,18,NaN,NaN,NaN,India,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,A lot less welcome now than last year,NaN,5,Less than 1 year
55407,64398,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62464,64439,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
62954,64442,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
64236,64452,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
india_df.to_json(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.json')
# created a json file which will have 1 dict and data in it

In [19]:
india_df.to_json(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.json', orient = 'records', lines= True)
# created a json which will have diff dict and data in it

In [22]:
test =pd.read_json(r'C:\Users\SACHIN KUMAR\Documents\survery\modified.json', orient = 'records', lines= True)
test.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,...,None,None,None,"Computer science, computer engineering, or sof...",None,None,A lot more welcome now than last year,NaN,6,4
1,22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,...,Easy,Appropriate in length,None,"Computer science, computer engineering, or sof...",None,None,Just as welcome now as I felt last year,50.0,10,2
2,58,I am a developer by profession,Yes,NaN,22,None,NaN,NaN,India,Indian rupee,...,Neither easy nor difficult,Too long,None,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,None,NaN,None,None
3,63,I am a student who is learning to code,Yes,21.0,17,None,NaN,NaN,India,None,...,Easy,Appropriate in length,No,None,Angular.js;Django;jQuery;Laravel;Vue.js,None,Not applicable - I did not use Stack Overflow ...,NaN,4,None
4,149,I am a developer by profession,Yes,36.0,31,Yearly,21000000.0,293196.0,India,Indian rupee,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",None,None,Somewhat more welcome now than last year,70.0,5,3